# Generated by Django 5.0.4 on 2024-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', help_text='Your full name', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(help_text='Your email address', max_length=254, verbose_name='email address')),
                ('message', models.TextField(help_text='Your message')),
            ],
            options={
                'verbose_name_plural': 'Contact Us Entries',
            },
        ),
    ]
